version: 2.1

orbs:
  envsubst: sawadashota/envsubst@1.1.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.9.5

jobs:
  upload_stickers:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install python dependencies
          command: pip3 install .

      - envsubst/install

      - run:
          name: Create config.json from template
          command: envsubst < config.template.json > config.json

      - run:
          name: Reupload and install stickers
          command: cat telegram-packs.txt | xargs sticker-import

      - add_ssh_keys

      - run:
          name: Add github to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: Commit stickerpack JSON's
          command: |
            git config --global user.email "eug-vs@keemail.me"
            git config --global user.name "eug-vs"
            # checkout development and bump the version
            git add .
            git commit -m "feat: add stickerpacks with CircleCI"
            git push -u origin master

workflows:
  version: 2

  test:
    jobs:
      - upload_stickers

